#!/usr/bin/python3


def build(ctx):
    # ctx(rule = 'blender -b -P ../models/interior/export_vc.py ${SRC}',source = 'cockpit/il86vc.blend',target = '../../il-86/SimObjects/Airplanes/Ilyushin-86/model/il86vc.gltf ../../il-86/SimObjects/Airplanes/Ilyushin-86/model/il86vc.bin')
    pass
