def build(ctx):
    ctx(rule='bash -c "mkdir -p ./il-86/SimObjects/Airplanes/Ilyushin-86/texture/"')
    # ctx(rule='bash -c "pwd"')
    ctx(rule='bash -c "cp -rvf ../texture/*.dds ./il-86/SimObjects/Airplanes/Ilyushin-86/texture/"')
    ctx(rule='bash -c "cp -rvf ../texture/*.jpg ./il-86/SimObjects/Airplanes/Ilyushin-86/texture/"')
