#!/usr/bin/python3

def build(ctx):
    ctx.recurse('interior')
    ctx.recurse('exterior')
    ctx(rule='cp ${SRC} ./il-86/SimObjects/Airplanes/Ilyushin-86/model/model.cfg',
        source='model.cfg')
    ctx(rule='cp ${SRC} ./il-86/SimObjects/Airplanes/Ilyushin-86/model/il86.xml',
        source='il86.xml')
    ctx(rule='cp ${SRC} ./il-86/SimObjects/Airplanes/Ilyushin-86/model/il86vc.xml',
        source='il86vc.xml')
